### ISSUE TITLE
Cannot save ops to file or as default. TypeError: get_text() missing 1 required positional argument: 'stringkeys'

### ISSUE THREAD

**Issue by Lilian-E** [MouseLand/suite2p#924]
Dear Suite2p community,

I noticed that I cannot save my settings to a file or as default settings. I have upgraded suite2p to the latest package, and I have also installed the latest version of the github code. I pulled the latest changes on the refactor branch (as was suggested in issue #914), and I still get the same TypeError. 

Below you will find the error information shown in Anaconda prompt after trying to save my ops settings as default. 

![ops_error](https://user-images.githubusercontent.com/64581124/220160790-9d2eed4d-842a-434f-b0e5-790b642239ba.png)

I am using version: v0.12.1.dev14+g2579413.

Your help will be greatly appreciated! 

Lilian

**Comment by chriski777** [comment]
Hi @Lilian-E, thanks for letting us know about this issue. I'm unfortunately having trouble replicating this on my end. What do you see when you use the command `suite2p --version` in your anaconda prompt?

**Comment by Renanvadico** [comment]
Can I jump into this? I also had the same problem.

My version is "suite2p v0.12.0"

**Comment by Lilian-E** [comment]
Hi @chriski777 

Initially I worked with version suite2p v0.12.0. After switching to the refractor branch and pulling changes, my version is now this: "suite2p v0.12.1.dev14+g2579413".

**Comment by chriski777** [comment]
Ah, I see. So, it turned out the change hasn't been pushed to the `main` branch yet. Could you try the following set of commands and see if works? 

```
pip uninstall suite2p
pip install git+https://github.com/MouseLand/suite2p.git@refactor
pip show suite2p
```
The package version should be 0.12.1.dev18+gb47b543 if done correctly. This is a temporary fix for now but we'll push the changes as soon as we can!

**Comment by Lilian-E** [comment]
Hi @chriski777, thanks a lot, this fix seems to work! 

Thanks for your help, I will close the issue.
